- name: "Update Apt Cache"
  apt: 
    update_cache: yes
  tags: installation

- name: "Install Common packages"
  apt:
    name: ['runc', 'python3-pip', 'docker.io', 'python3-venv', 'docker-compose', 'qemu-guest-agent']
    state: latest
  tags: installation, kubernetes, packages

- name: "Install Common packages"
  apt:
    name: ['qemu-guest-agent']
    state: latest
  tags: installation, packages, all

- hosts: all
  become: yes
  tasks:
    - name: install nfs-utils
      apt:
        name: nfs-utils
        state: latest

    - name: Create a mountable directory if it does not exist
      file:
        path: /mnt/web_storage
        state: directory
        owner: rhlinuxuzer
        group: rhlinuxuzer
        mode: '0775'
    - name: Mount volumn
      shell: sudo mount {{storage}}:/home/rhlinuxuzer/nfs_test /mnt/web_storage
      tags: 